# @package _global_
defaults:
  - override /data: egobody/train_stage1
  - override /model: gvhmr/gvhmr_pl
  - override /endecoder: gvhmr/v1_amass_local_bedlam_cam
  - override /optimizer: adamw_2e-4
  - override /scheduler_cfg: epoch_half_200_350
  - override /network: gvhmr/relative_transformer
  - override /callbacks:
      - simple_ckpt_saver/every10e_top100
      - prog_bar/prog_reporter_every0.1
      - train_speed_timer/base
      - lr_monitor/pl
  - _self_

exp_name: egobody_view1_stage1_ego
data_name: egobody_view1

# 只训练 ego head
model:
  freeze_backbone: true
  freeze_exo_head: true
  freeze_ego_head: false
  copy_exo_to_ego: true
  vis_every_n_steps: 50

pipeline:
    _target_: hmr4d.model.gvhmr.pipeline.gvhmr_pipeline.Pipeline
    args_denoiser3d: ${network}
    args:
        endecoder_opt: ${endecoder}
        normalize_cam_angvel: True
        weights:
            cr_j3d: 500.
            transl_c: 1.
            cr_verts: 500.
            j2d: 1000.
            verts2d: 1000.

            transl_w: 1.
            static_conf_bce: 1.

        static_conf:
            vel_thr: 0.15
            
# datamodule
data:
  loader_opts:
    train:
      batch_size: 32
      num_workers: 8
    val:
      batch_size: 1
      num_workers: 2

pl_trainer:
  # precision: 32
  precision: 16-mixed
  log_every_n_steps: 10
  gradient_clip_val: 0.5
  max_epochs: 200
  check_val_every_n_epoch: 5
  devices: 1
  

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${output_dir}
  name: "tb"
  version: ${now:%m%d_%H%M%S}